import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ChevronDown,Sun,Moon,ArrowRight,Copy,Check,Activity,Calculator,Shield,ChartNoAxesCombined,Menu,X}from'lucide-react';import'./styles.css';

const tools=[{name:'Monte Carlo Simulator',icon:ChartNoAxesCombined,desc:'Explore possible trading outcomes through randomized simulations.'},{name:'Breakeven Win Rate',icon:Calculator,desc:'Find the win rate required to break even at any risk-to-reward ratio.'},{name:'Loss Streak Simulator',icon:Activity,desc:'Simulate 50–500 trades and explore possible losing streaks.'},{name:'Drawdown Simulator',icon:Shield,desc:'Model static and intraday trailing drawdown trade by trade.'},{name:'Consistency Calculator',icon:ChartNoAxesCombined,desc:'Understand biggest-day limits and the consistency you need.'},{name:'Profit Split Calculator',icon:Calculator,desc:'Calculate your payout from net profit and a profit split.'}];
const firms=[{name:'Example Fund',discount:'20%',code:'ENTRY20'},{name:'Orbit Capital',discount:'15%',code:'SPACE15'},{name:'Nova Funding',discount:'10%',url:'#'}];

function App(){const[dark,setDark]=useState(true);const[mobile,setMobile]=useState(false);const[copied,setCopied]=useState('');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);const copy=c=>{navigator.clipboard?.writeText(c);setCopied(c);setTimeout(()=>setCopied(''),1400)};return <div className="site">
<Background dark={dark}/>
<header className="header"><a className="brand" href="#"><span className="brand-mark">T</span><span>TheEntryExit</span></a><nav className={mobile?'nav open':'nav'}><Dropdown label="Tools" items={tools.map(t=>t.name)}/><Dropdown label="Prop Firms" items={['All Prop Firms','Discounts']}/><button className="nav-link">Resources</button><Dropdown label="Social" items={['YouTube','X / Twitter','Discord']}/></nav><div className="header-actions"><button className="theme" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="mobile-toggle" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
<main>
<section className="hero"><div className="hero-glow"/><div className="eyebrow"><span className="pulse"/>TRADING COMMAND CENTER</div><h1>Trade beyond<br/><span>the obvious.</span></h1><p>Tools, simulators and prop-firm intelligence built for traders who want to understand the numbers behind every decision.</p><div className="hero-actions"><a className="primary" href="#tools">Explore Tools <ArrowRight size={17}/></a><a className="secondary" href="#firms">View Prop Firms</a></div></section>
<section className="promo"><div><span className="promo-kicker">LIMITED DEALS</span><strong>Biggest prop firm discounts running right now.</strong></div><a href="#firms">View deals <ArrowRight size={16}/></a></section>
<section className="ticker" aria-label="Market instruments">{['XAUUSD','NAS100','US30','BTCUSD','EURUSD','GBPUSD','SPX500','USDJPY'].map((x,i)=><span key={x}><b>{x}</b><em>{i%2?'24/7':'LIVE'}</em></span>)}</section>
<section id="tools" className="section"><div className="section-head"><div><span className="eyebrow">THE TOOLKIT</span><h2>Built to answer the<br/><span>questions traders actually ask.</span></h2></div><a href="#tools" className="text-link">View all tools <ArrowRight size={16}/></a></div><div className="tool-grid">{tools.map((t,i)=><ToolCard key={t.name} tool={t} index={i}/>)}</div></section>
<section id="firms" className="section firms-section"><div className="section-head"><div><span className="eyebrow">PROP FIRMS</span><h2>Current <span>offers.</span></h2></div><a href="#firms" className="text-link">Prop firm page <ArrowRight size={16}/></a></div><div className="firm-grid">{firms.map(f=><div className="firm-card" key={f.name}><div className="firm-logo">{f.name[0]}</div><div className="firm-info"><strong>{f.name}</strong><span>{f.discount} discount</span></div>{f.code?<button className="code-btn" onClick={()=>copy(f.code)}>{copied===f.code?<><Check size={15}/>Copied</>:<><Copy size={15}/>Copy {f.code}</>}</button>:<a className="go-btn" href={f.url}>Go to <ArrowRight size={15}/></a>}</div>)}</div></section>
<section className="resources"><div className="resource-inner"><span className="eyebrow">COMING LATER</span><h2>Trading resources,<br/><span>without the noise.</span></h2><p>Guides, market references and educational resources will live here. We'll build this section when you're ready.</p></div></section>
</main><footer><div className="footer-brand"><a className="brand" href="#"><span className="brand-mark">T</span><span>TheEntryExit</span></a><p>A trading command center for better decisions.</p></div><div className="footer-links"><a href="#tools">Tools</a><a href="#firms">Prop Firms</a><a href="#contact">Contact Us</a><Dropdown label="Social" items={['YouTube','X / Twitter','Discord']}/></div><div className="copyright">© 2026 TheEntryExit</div></footer></div>}

function Dropdown({label,items}){return <details className="dropdown"><summary>{label}<ChevronDown size={14}/></summary><div className="dropdown-menu">{items.map(x=><a href="#" key={x}>{x}</a>)}</div></details>}
function ToolCard({tool,index}){const Icon=tool.icon;return <a href="#" className="tool-card"><div className="tool-number">0{index+1}</div><div className="icon-box"><Icon size={20}/></div><h3>{tool.name}</h3><p>{tool.desc}</p><span className="card-arrow"><ArrowRight size={17}/></span></a>}
function Background({dark}){return <div className="space-bg" aria-hidden="true"><div className="stars"/><div className="nebula n1"/><div className="nebula n2"/><div className="sun"/><div className="orbit o1"/><div className="orbit o2"/></div>}
createRoot(document.getElementById('root')).render(<App/>);